### ISSUE TITLE
LysinsDB®-Data: Setup

### ISSUE THREAD

**Issue by SequomicsResearch** [LysinsDB/LysinsDB-Data#1]
**Project Setup for LysinsDB®-Data:**
- .gitignore,
- .gitattributes,
- .eslintignore,
- .jscsrc — with Preset: {jQuery-style-guide},
- .jshintignore,
- .npmignore,
- .nvmrc,
- .travis.yml,
- LICENSE,
- *.sublime-project, and
- README.md

Other(s):
- _shell script file_ — `build.sh`

**Note**: Initials of LysinsDB®-Data.

**Comment by iamprabhat** [comment]
[SHA](https://github.com/LysinsDB/LysinsDB-Data/commit/538aee9d6001d991458092eaac8460a535594bc7) — **Done**.
