### ISSUE TITLE
LysinsDB®-Data: Build Setup

### ISSUE THREAD

**Issue by SequomicsResearch** [LysinsDB/LysinsDB-Data#2]
**Build Setup for LysinsDB®-Data:**
- Using [Node.js](https://nodejs.org/en/)®,
- Using [NPM](https://www.npmjs.com/),
- Using [Rollup](http://rollupjs.org/) — {rollup.config.js},
- Using [Grunt](http://gruntjs.com/), — {Gruntfile.js and karma.conf.js} and
- Using Shell Script.

**Include(s):** in to {_/config/rules/_} directory
- .jscsrc — with Preset: {node-style-guide}, and
- .eslintrc.

**Other(s):**
- requirements.txt
- package.json
- AUTHOR.txt
- ARCHITECTURE.md
- BUILDING.md
- CHANGELOG.md
- CODEOFCONDUCT.md
- CONTRIBUTING.md
- DEPLOYING.md
- GOVERNANCE.md

Help:
- JavaScript dependency management — [{?}](https://medium.com/@trek/last-week-i-had-a-small-meltdown-on-twitter-about-npms-future-plans-around-front-end-packaging-b424dd8d367a)

**Note**: Initial Build of LysinsDB®-Data.

**Comment by iamprabhat** [comment]
[SHA](https://github.com/LysinsDB/LysinsDB-Data/commit/6e05a8efd1d0705ae2bbaea2aadb37a74046bd79) — **Done**.
